#######################################################
# 
# Ellipse.py
# Python implementation of the Class Ellipse
# Generated by Enterprise Architect
# Created on:      08-����-2021 19:52:00
# Original author: tealh
# 
#######################################################
import TwoDim


class Ellipse(TwoDim):
    def draw(self):
        pass

    def fill(self):
        pass
