#######################################################
# 
# Figure.py
# Python implementation of the Class Figure
# Generated by Enterprise Architect
# Created on:      08-����-2021 19:52:00
# Original author: tealh
# 
#######################################################

import tkinter


class Figure:
    # points = []
    # obj = []
    def __init__(self):
        self.line_color = "black"
        self.points = []
        self.obj = []

    def draw(self):
        pass

    def get_line_color(self):
        return self.line_color

    def get_points(self):
        return self.points

    def move(self):
        pass

    def set_line_color(self, color):
        self.line_color = color

    def set_points(self, points):
        self.points = points

    def delete(self, canva):
        for i in self.obj:
            canva.delete(i)