#######################################################
# 
# Interval.py
# Python implementation of the Class Interval
# Generated by Enterprise Architect
# Created on:      08-����-2021 19:52:00
# Original author: tealh
# 
#######################################################
from OneDim import OneDim
from Point import Point
import tkinter

class Interval(OneDim):
    def __init__(self, x1, y1, x2, y2, color):
        OneDim.__init__(self)
        self.line_color = color
        self.points.append(Point(x1, y1))
        self.points.append(Point(x2, y2))

    def draw(self, canva):
        self.obj.append(canva.create_line(self.points[0].get_x(), self.points[0].get_y(), self.points[-1].get_x(), self.points[-1].get_y(), width=3, fill=self.line_color))

    # def leftclick(self, event):
    #     self.points.append(Point(event.x, event.y))
    #     self.points.append(Point(event.x, event.y))
    #
    # def mouseMotionWithLeftButtonPressed(self, event):
    #     self.delete(self.canva)
    #     self.points[-1].point_change(event.x, event.y)
    #     self.draw(self.canva)
    #     # print ('Motion')
