#######################################################
# 
# OneDim.py
# Python implementation of the Class OneDim
# Generated by Enterprise Architect
# Created on:      08-����-2021 19:52:00
# Original author: tealh
# 
#######################################################
from Figure import Figure


class OneDim(Figure):
    def __init__(self):
        Figure.__init__(self)

    def move(self, delta):
        pass
