#######################################################
# 
# PolygonalLine.py
# Python implementation of the Class PolygonalLine
# Generated by Enterprise Architect
# Created on:      08-март-2021 19:52:00
# Original author: tealh
# 
#######################################################
import OneDim
import Interval


class PolygonalLine(OneDim):
    m_Interval = Interval()
