#######################################################
# 
# Polygon.py
# Python implementation of the Class Polygon
# Generated by Enterprise Architect
# Created on:      08-����-2021 19:52:00
# Original author: tealh
# 
#######################################################
from Point import Point
from TwoDim import TwoDim


class Polygon(TwoDim):
    def __init__(self, points, line_color, fill_color,  tags):
        self.tags = tags
        TwoDim.__init__(self)
        self.line_color = line_color
        self.fill_color = fill_color
        self.points = points
        self.tags = tags
        self.id = None

    def draw(self, canvas):
        self.id = canvas.create_polygon(self.points, outline=self.line_color,
                                        fill=self.fill_color, width=3, tags=(self.tags,))
        self.obj.append(self.id)

    def fill(self):
        pass
