#######################################################
# 
# RegularPolygon.py
# Python implementation of the Class RegularPolygon
# Generated by Enterprise Architect
# Created on:      08-март-2021 19:52:00
# Original author: tealh
# 
#######################################################
import Polygon

class RegularPolygon(Polygon):
    def get_sides_num():
        pass

    def set_sides_num(value):
        pass