#######################################################
# 
# Rhombus.py
# Python implementation of the Class Rhombus
# Generated by Enterprise Architect
# Created on:      08-����-2021 19:52:00
# Original author: tealh
# 
#######################################################
from Polygon import Polygon
from Point import Point


class Rhombus(Polygon):
    def __init__(self, points, line_color, fill_color, tags):
        self.line_color = line_color
        self.fill_color = fill_color
        self.tags = tags
        self.id = None

        x1, y1, x2, y2 = tuple(points)
        self.points = [Point(x1, (y1 + y2) / 2), Point((x1 + x2) / 2, y1),
                       Point(x2, (y1 + y2) / 2), Point((x1 + x2) / 2, y2)]
        Polygon.__init__(self, self.points, line_color, fill_color, tags)

    def get_sides_num(self):
        pass

    def set_sides_num(self):
        pass
