#######################################################
# 
# RightTriangle.py
# Python implementation of the Class RightTriangle
# Generated by Enterprise Architect
# Created on:      08-март-2021 19:52:00
# Original author: tealh
# 
#######################################################
import Polygon


class RightTriangle(Polygon):
    pass
