#######################################################
# 
# Class1.py
# Python implementation of the Class Class1
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:03
# Original author: vasya
# 
#######################################################


class Class1:
    pass