#######################################################
# 
# Ellipse.py
# Python implementation of the Class Ellipse
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:05
# Original author: tealh
# 
#######################################################
import TwoDim
import TwoPoints

class Ellipse(TwoDim, TwoPoints):
    def draw():
        pass

    def fill():
        pass