#######################################################
# 
# Figure.py
# Python implementation of the Class Figure
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:06
# Original author: tealh
# 
#######################################################


class Figure:
    line_color = #000000
    def draw():
        pass

    def get_line_color():
        pass

    def get_points():
        pass

    def move():
        pass

    def set_line_color(color):
        pass