#######################################################
# 
# Interval.py
# Python implementation of the Class Interval
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:07
# Original author: tealh
# 
#######################################################
import OneDim

class Interval(OneDim):
    def draw():
        pass