#######################################################
# 
# Line.py
# Python implementation of the Class Line
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:09
# Original author: tealh
# 
#######################################################
import Ray

class Line(Ray):
    pass