#######################################################
# 
# ManyPoints.py
# Python implementation of the Class ManyPoints
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:10
# Original author: tealh
# 
#######################################################
import TwoDim

class ManyPoints(TwoDim):
    pass