#######################################################
# 
# OneDim.py
# Python implementation of the Class OneDim
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:11
# Original author: tealh
# 
#######################################################
import Figure

class OneDim(Figure):
    def move():
        pass