#######################################################
# 
# PolygonalLine.py
# Python implementation of the Class PolygonalLine
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:12
# Original author: tealh
# 
#######################################################
import OneDim
import Interval

class PolygonalLine(OneDim):
    m_Interval= Interval()
