#######################################################
# 
# Polygon.py
# Python implementation of the Class Polygon
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:11
# Original author: tealh
# 
#######################################################
import ManyPoints
import TwoDim

class Polygon(ManyPoints, TwoDim):
    def draw():
        pass

    def fill():
        pass