#######################################################
# 
# Ray.py
# Python implementation of the Class Ray
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:13
# Original author: tealh
# 
#######################################################
import Interval

class Ray(Interval):
    pass