#######################################################
# 
# RegularPolygon.py
# Python implementation of the Class RegularPolygon
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:13
# Original author: tealh
# 
#######################################################
import Polygon
import TwoPoints

class RegularPolygon(Polygon, TwoPoints):
    def get_sides_num():
        pass

    def set_sides_num(value):
        pass