#######################################################
# 
# Rhomb.py
# Python implementation of the Class Rhomb
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:14
# Original author: tealh
# 
#######################################################
import TwoPoints
import Polygon

class Rhomb(TwoPoints, Polygon):
    pass