#######################################################
# 
# RightTriangle.py
# Python implementation of the Class RightTriangle
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:15
# Original author: tealh
# 
#######################################################
import TwoPoints
import Polygon

class RightTriangle(TwoPoints, Polygon):
    pass