#######################################################
# 
# TwoDim.py
# Python implementation of the Class TwoDim
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:15
# Original author: tealh
# 
#######################################################
import Figure

class TwoDim(Figure):
    fill_color = #ffffff
    def fill():
        pass

    def get_fill_color():
        pass

    def move():
        pass

    def set_fill_color(color):
        pass