#######################################################
# 
# TwoPoints.py
# Python implementation of the Class TwoPoints
# Generated by Enterprise Architect
# Created on:      03-март-2021 9:28:16
# Original author: tealh
# 
#######################################################
import TwoDim

class TwoPoints(TwoDim):
    def get_is_regular():
        pass

    def set_is_regular(value):
        pass